### PR TITLE
Don't use the default install directory

### PR DESCRIPTION
**Pull request by PanuSaukko**
Want to have a note that you should not install SCCM to an operating system partition. It is a bad default directory that should never be used in a production environments.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@PanuSaukko : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @PanuSaukko for the contribution. 😃 
Reference Twitter thread https://twitter.com/panusaukko/status/1116681735184486401
I'm checking with the feature team on this, stay tuned.

**Comment by aczechowski** [comment]
@PanuSaukko, the challenge is that I'm having a hard time stating to not use a wizard *default*. So I think the way to pivot this note is to state the implications of keeping the default. What are the primary concerns for using the default install directory? I think we could call those out in this note, and then let the admin make up their own mind.

**Comment by PanuSaukko** [comment]
Yep. I understand that it might difficult to say that the default installation directory is not very good option. Maybe you should change the default.. :-)

I see two main issues using OS partition as a default SCCM installation directory:
1) SCCM might consume all the free disk space on the OS partition and you might run into issues the OS partition runs out of free disk space. 
2) SCCM installation directory requires a fast disk and OS partition might have a slow disk. This is especially true if you are installing SCCM on an Azure VM.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @PanuSaukko, I reworded the note based on your input. Let me know if you're ok with it?

**Comment by PanuSaukko** [comment]
Much, much better now! Great work Aaron!

**Comment by aczechowski** [comment]
Oops, need it open to merge it live 😉

**Comment by aczechowski** [comment]
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *could* be today (Friday, 22 May) around 11:00 Pacific time. (If not, it will be next Tuesday due to the US holiday on Monday.) No further action needed from you.

**Pull request merged**
