### PR TITLE
Update task-sequence-steps.md

### PR DESCRIPTION
**Pull request by Rashid29**
Following changes are proposed
-3556028-->  

To add this step in the task sequence editor, select **Add**, select **General**, and select **Run PowerShell Script**.

Note: Signed Powershell script must be saved in Unicode format and not ANSI(default) to work with this step

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Rashid29 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @Rashid29 for the contribution. I'm checking with the feature team.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
