### PR TITLE
Update support-for-sql-server-versions.md

### PR DESCRIPTION
**Pull request by gokularvind**

### CODE REVIEW

**Comment by aczechowski** [comment]
@mestew is this the same topic you are working on a revision? A good suggestion to include a bit on compatibility level.

**Comment by mestew** [comment]
@aczechowski Let me firm up some of the details but I totally agree this should be in the doc.

**Comment by mestew** [comment]
Better markdown of proposed change below and txt of markdown attached. This would go well right under the "Database collation" entry under the "required configurations" heading rather than under the "supported versions" heading . 

<--!Existing text--> 
 **Database collation:**  
 At each site, both the instance of SQL Server that is used for the site and the site database must use the following collation: **SQL_Latin1_General_CP1_CI_AS**. 
Configuration Manager supports two exceptions to this collation to meet standards that are defined in GB18030 for use in China. For more information, see [International support in System Center Configuration Manager](../../../core/plan-design/hierarchy/international-support.md).  


**Database Compatibility Level:**
Configuration Manager requires that the compatibility level for the site database be no less than the lowest supported SQL Server version for your Configuration Manager version. For instance, beginning with version 1702, you will need to have a [database compatibility level](https://docs.microsoft.com/sql/relational-databases/databases/view-or-change-the-compatibility-level-of-a-database) greater than or equal to 110. 
 

[PR338-gokularvind.txt](https://github.com/MicrosoftDocs/SCCMdocs/files/1603778/PR338-gokularvind.txt)

**Comment by aczechowski** [comment]
we already fixed this content, closing this PR

**Pull request closed without merging**
