### PR TITLE
Update upgrade-on-premises-infrastructure.md

### PR DESCRIPTION
**Pull request by SLeuthold**
### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

@Article_Author please review (look at the `author` metadata tag)

### CODE REVIEW

**Comment by PRMerger17** [comment]
@SLeuthold : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
@SLeuthold did you close this on purpose? In this closed state, that's saying: "nevermind, ignore." If you want this contribution to be considered/reviewed, reopen the pull request.

**Comment by SLeuthold** [comment]
😐 I closed by mistake! I’ll correct it sir!





[cid:InvokeV2_320x123_a1057048-27ef-466c-97e5-e700c239d335.png]<http://www.InvokeSM.com>

[cid:Twitter_b17288c0-c42e-4e7b-bc77-033c4322b063.png]   <https://twitter.com/InvokeSM>  [cid:Facebook_df83b2d8-63dc-4240-81e8-612606d7af58.png]    <https://www.facebook.com/InvokeSM/>  [cid:LinkedIn_c54ffc3c-9f7d-485b-81ad-8b3c147d5a66.png]  <https://www.linkedin.com/company/7798865/>



Stephen Leuthold / Principal Consultant
Stephen.Leuthold@InvokeSM.com<mailto:Stephen.Leuthold@InvokeSM.com>
+1 (713) 553-1639

Invoke, LLC
+1 (713) 909-0411
118 Vintage Park Blvd. #W
Houston, Texas 77070
http://InvokeSM.com




________________________________

**Comment by SLeuthold** [comment]
Open!

**Comment by aczechowski** [comment]
Great thanks. As for the content - can you provide some additional context? Did this come up in forums or a support case?

**Comment by SLeuthold** [comment]
This came up from personal experience. There was a 2012 R2 OS running primary site server, DP, and MP. After performing in-place upgrade of OS to 2016, it wiped the “Software\Microsoft\SMS” value from HKLM\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths. This caused a backlog in the outbox on all state migration points.

**Comment by aczechowski** [comment]
Thanks @SLeuthold for the additional information. I'm reviewing with the engineering team. Stay tuned...

**Comment by PRMerger16** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by aczechowski** [comment]
Automation bug, reopening

**Comment by aczechowski** [comment]
Resolve merge conflict, and (finally) make some edits based on input from engineering. 
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Thursday, 3 January) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
