### PR TITLE
The ability to remove the Intune connection for existing on-premises …

### PR DESCRIPTION
**Pull request by MSFTJerryAb**
…MDM customers is planned for a future a release.

I don’t think it is crystal clear that this only applies to new setups, though it says “to configure” – I think it would be reasonable to remove the connector in 1810, based on what we docd. Fixing the related issue requires contacting support.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@MSFTJerryAb : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @MSFTJerryAb for the contribution. I'm going to #sign-off on this, although have some editorial suggestions. I'll be making some changes in this article in the near future, so will pick up my edits then. 😄

**Comment by tfosmark** [comment]
I've asked @aczechowski a follow-up question offline and will hold off the merge until he has a chance to review and respond. Thanks for your patience.

#hold-off

**Comment by aczechowski** [comment]
I'll followup with @MSFTJerryAb offline. Closing this PR.

**Pull request closed without merging**
