### PR TITLE
Update certificates-for-cloud-management-gateway.md

### PR DESCRIPTION
**Pull request by adsshepherd**
Fixing broken URLs

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

@Article_Author please review (look at the `author` metadata tag)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@adsshepherd : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Ooops, thanks @adsshepherd for catching that! Looks good, #sign-off

**Comment by aczechowski** [comment]
@adsshepherd this should be live with the next daily publishing process. Right now that *should* be later today around 11:00 Pacific time.

**Comment by adsshepherd** [comment]
Perfect Aaron, thanks very much.

Best, Adam

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

**Pull request merged**
