### PR TITLE
Update configure-wake-on-lan.md

### PR DESCRIPTION
**Pull request by russrimm**
wakeup is greyed out when connected to a CAS

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@russrimm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
Hey @russrimm Thanks for the update to the doc! I tweaked the wording CAS -> Central Administration Site, but kept everything else.  

#sign-off

**Comment by PRMerger10** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off 
Decided to add metadata change while I was here =)

**Pull request merged**
