### PR TITLE
Remove "Configure auto-enrollment of devices to Intune"

### PR DESCRIPTION
**Pull request by vanyuale**
Section "Configure auto-enrollment of devices to Intune" is not required for co-management, because related to direct Windows PCs enrollment to Intune (Autopilot or Intune-only managed).

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@vanyuale : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @vanyuale for submitting the contribution. At first glance I'm inclined to decline the change; we worked with the engineering team to structure this tutorial with their recommended process. Can you provide some additional explanation and justification as to why you think this isn't needed?

**Comment by vanyuale** [comment]
Because currently User Scope setting is not affecting co-management enrolment, because it is working even if Scope set to None or Group. That is affecting only direct enrolment (user driven enrolment). So, that is something required for Intune managed devices, but not for Co-Management configuration. Hope it make sense.
Thank you.

**Comment by aczechowski** [comment]
Comment from the feature team:

> in short we need to keep user flows as is. With new changes  sccm tries device token code path of device is capable and if for whatever reason enrollment fails it falls back to user token path. In short user path is not deprecated. So user related docs still make sense.

So I'm closing the pull request. Thanks again for taking the time to make the contribution.

**Pull request closed without merging**
