### PR TITLE
Added CSP License Information.

### LINKED ISSUE #749: Obtaining media for other licensing types
Please specify how to obtain installation media and license key when ConfigMgr is licensed via Intune, EMS,  Microsoft 365 etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295caa58-e5d5-4b95-9287-62af7e118241
* Version Independent ID: 77e831e1-ff78-2b4e-2d90-341bb4c3b3a4
* Content: [Get installation media - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/get-install-media)
* Content Source: [sccm/core/servers/deploy/install/get-install-media.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/get-install-media.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #749 .

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved the merge conflict (duplicate "from the").

**Pull request merged**
