### PR TITLE
Added Run PowerShell Script task to Task Sequence run as account

### PR DESCRIPTION
**Pull request by jason4tw**
Added Run PowerShell Script task to Task Sequence run as account and added local admin account requirement for the Run PowerShell Script task per the comments at https://www.reddit.com/r/SCCM/comments/c8parf/running_powershell_script_during_ts_failing/ by /u/vsoro00 (who I'm assuming is Vlad Sorokin).

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jason4tw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be today (Friday, 5 July) around 11:00 Pacific time. No further action needed from you.

**Comment by PRMerger17** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Comment by ktoliver** [comment]
> Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

@aczechowski I'll open a bug for this.

**Comment by ktoliver** [comment]
Bug for PRMerger error in employee detection: https://ceapex.visualstudio.com/SRE/_workitems/edit/103643

**Pull request merged**
