### PR TITLE
Update set-up.md

### PR DESCRIPTION
**Pull request by zdvorak**
Removed link to DA portal to prevent users who find the docs from being able to onboard

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@zdvorak : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @zdvorak. 

There's also a link in the [tutorial](https://docs.microsoft.com/en-us/sccm/desktop-analytics/tutorial-office-365). Can you make that edit as well?

When you make the commit for that, if you add it to the *same branch* as this pull request (patch-1), then it will automatically get added to this pull request. Not a big deal to do a separate branch and separate pull request if that's easier for you.

Let me know if you have any questions.

**Comment by zdvorak** [comment]
@aczechowski Done!

**Comment by aczechowski** [comment]
@zdvorak hm, not seeing the change. I know you're travelling right now, so I'll insert that other change myself just to get this published.

**Comment by aczechowski** [comment]
#sign-off

p.s. @zdvorak as a Microsoft FTE, in the future, please use sccmdocs-pr repo. Use the same process, just after you click Edit on the article, switch the URL to sccmdocs **-pr**. 😃

**Pull request merged**
