### PR TITLE
Add note regarding using OS Upgrade Package

### PR DESCRIPTION
**Pull request by frankroj**
Add note regarding using OS Upgrade Package for new Windows installations

### CODE REVIEW

**Comment by PRMerger7** [comment]
@frankroj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@frankroj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@frankroj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @frankroj for the contribution! This looks good.
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that should be _next week_ (Wednesday, 2 January) around 11:00 Pacific time. (There's a publishing freeze for the holidays.) No further action needed from you.

**Comment by PRMerger14** [comment]
@GitHubber17 : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Pull request merged**
