### PR TITLE
Update text to reflect post 1710 Support lifecycle

### PR DESCRIPTION
**Pull request by JohnRajunas**
The change I am proposing is designed to more accurately reflect the Support lifecycle changes for Configuration Manager Current Branch that were made after the "1710" release.   The text I have added is text directly from the "Support for Current Branch" topic that I link to, which would make the reference in this topic a exact duplicate of the introduction to the details in the "Support for CM CB" topic, which I believe is more accurate and up to date.  I hope this will be acepted

### CODE REVIEW

**Comment by PRMerger13** [comment]
@JohnRajunas : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @JohnRajunas, good catch. Can you please make the following two changes before I approve?
- Remove "en-us/" from the URL so that it is language neutral
- Add a period after the link before the final sentence

**Comment by JohnRajunas** [comment]
Will do – complementing momentarily

**Comment by PRMerger7** [comment]
@JohnRajunas : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
