### PR TITLE
Adding 'Application Copy' instructions with update to TOC.

### PR DESCRIPTION
**Pull request by ChrisKibble**
Created new file with instructions on how to copy an application in Configuration Manager.  Updated TOC to link to this file.

@aczechowski wasn't confident on how you wanted to see the metadata on new files so I commented a few items out to be adjusted by whomever you manage this.

This is a submission for #MMS2019Docathon

### CODE REVIEW

**Comment by PRMerger17** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by ChrisKibble** [comment]
@aczechowski can you please review?

**Comment by aczechowski** [comment]
This change appears to be a duplicate of #1464 (it has the same commit at least). So I'll keep this PR closed, and exclude it from the contest counts. We'll work through the new content in #1464.

**Comment by ChrisKibble** [comment]
Thanks @aczechowski - wasn't an intentional dupe, I hadn't quite figured out yet when I did this change earlier in the week that I should be branching when making changes outside of the Edit button or each new PR includes all the stuff from my previous PRs.  If nothing else, this contest has forced me to learn GIT :-)

**Pull request closed without merging**
