### PR TITLE
updated URL reference

### PR DESCRIPTION
**Pull request by daveRendon**
corrected URL https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/understand/upgrade-update-install.md

### CODE REVIEW

**Comment by mestew** [comment]
@daveRendon 
Hi Dave. I am seeing that the link for Upgrade, Update and Install works properly from 
the article: https://docs.microsoft.com/en-us/sccm/core/servers/manage/updates 
Are you seeing that it is not? 
The shorthand notation /sccm/core/understand/upgrade-update-install should work. We shouldn't point to GitHub URLs directly.

**Comment by daveRendon** [comment]
@mestew 
Hi Megan, 
If you go to https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/servers/manage/updates.md

and then click on the URL reference "About upgrade, update, and install" you will get a kindly 404: 

image





https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/understand/upgrade-update-install

Could you please review? Appreciate your follow up on this, thank you!

**Comment by mestew** [comment]
@daveRendon 
Hi Dave, 
The root of the problem you see on GitHub is that a lot of times when we are specifying links in the docs, we drop the .md file extension. This is totally fine for docs.microsoft.com and the links works. This is the end result that we code to. 
However, when GitHub auto-creates the blob link, it doesn't like not having the .md dropped. If you look at the raw markdown for the file, you can see sometimes we add the .md and other times we don't. When we do add the .md, the GitHub blob link is fine. https://raw.githubusercontent.com/MicrosoftDocs/SCCMdocs/master/sccm/core/servers/manage/updates.md 
We typically don't write the docs for browsing from GitHub. Most of the users on here will just append  .md to the url or if needed or just browse to the file.

**Comment by aczechowski** [comment]
Closing this PR based on Meghan's response

**Pull request closed without merging**
