### PR TITLE
Clarified note on All Users collection.

### LINKED ISSUE #481: Add Note per customer case
Hey – per feedback from a customer case and our own research, we would like to modify the following note in this document.

•	Current note:
Note
When you have the All users collection selected for the Intune subscription, you are not allowed to add a rule to exclude collections. Create a new collection based on the All users collection, verify that the collection contains the users that you expect, and then edit the Intune subscription to use the new collection. You can exclude user collections from the new collection to migrate users. 

•	Suggested update:

Note
When you have the All users collection selected for the Intune subscription, you are not allowed to add a rule to exclude collections. Create a new collection based on the All users collection, verify that the collection contains the users that you expect, and then edit the Intune subscription to use the new collection. You can exclude user collections from the new collection to migrate users. 
If All Users AND All Groups are included in the SCCM/Hybrid Intune user collection, and a test user in a user collection is excluded from the SCCM/Hybrid Intune user collection, and the user in the excluded user collection is in any group, the user won't be excluded from the SCCM/Hybrid Intune user collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4913cd11-dd09-791f-af96-9849efa08ef9
* Version Independent ID: 4e271b5d-8d9f-7837-867e-1fc1fffd3242
* Content: [Change the MDM authority for specific users (mixed MDM authority) - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-mixed-authority#feedback)
* Content Source: [sccm/mdm/deploy-use/migrate-mixed-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-mixed-authority.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #481

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger19** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
