### PR TITLE
Update cloud-management-gateway-faq.md

### PR DESCRIPTION
**Pull request by RobYork**
### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger17** [comment]
@RobYork : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@RobYork : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@RobYork : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

Note to reviewer: I purposefully commented the first section; I'll address it later offline with Rob.

@RobYork, as a Microsoft FTE, in the future, please use sccmdocs-pr repo. Use the same process, just after you click Edit on the article, add **-pr** to the URL for sccmdocs-pr. 😄

**Comment by aczechowski** [comment]
#hold-off

**Comment by PRMerger15** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
