### PR TITLE
Removed - Install WSUS on a Dedicated Instance

### PR DESCRIPTION
**Pull request by JordanTheITGuy**
Asking around a large number of people at MMS no one has installed WSUS on it's own dedicated instance no one even had heard that was a recommended best practice. Can we validate with Rae - since she's here - if we still really even need to do this? And if we don't lets remove it.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger7** [comment]
@JordanTheITGuy : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by mestew** [comment]
@JordanTheITGuy 
Hey, wait a sec...I totally do that! =) I'll chat with Rae about it when she gets back from having fun at MMS. 
image

**Comment by dudeso** [comment]
@mestew this isn’t something I have ever seen to be honest but you likely know better than me! Rae is here at MMS as well, we’ll ping you tomorrow.

**Comment by aczechowski** [comment]
Hey @JordanTheITGuy - we had some further chats post-MMS. Thank you for making the contribution, but we decided to keep the guidance. @mestew is a WSUS guru, and for troubleshooting purposes she does recommend separate instances. And this guidance has been around for years, see [2012 R2 content](https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/hh692394\(v%3dtechnet.10\)). Sure, guidance changes, but in this instance we generally think this is a good thing. With that, just because it's a best practice doesn't mean everyone needs to follow it. If you have some solid reasons why you *don't* want to do this, perhaps we could add those as notes to this section instead. I'm a fan of providing the data/details, and letting the individual decide what's best for their environment.

**Comment by JordanTheITGuy** [comment]
👍

Sounds good. The big thing I would put out there then is that if it's a separate instance that means from a licensing standpoint it needs to be express. When you shift to using a SQL express database instead that changes how and what types of maintenance options you have available to you from a scheduling standpoint and further complicates things as now you have two separate instances on the server that you need to connect to and configure/monitor. 

I would be curious if via telemetry/SUP maintenance job information that has been being added in you could actually see the number of organizations that run it separately. 

Also Secondary Site servers that are out there with SUPs on them confuse the issue further.

**Pull request closed without merging**
