### PR TITLE
Intune license required when enabling co-management

### PR DESCRIPTION
**Pull request by byteben**
When using the "Sign In" option during the co-management wizard, if the account used does not have a valid Intune license, sign in will fail.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@byteben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@aczechowski @mestew , please provide guidance on this PR:

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by jborsecnik** [comment]
@aczechowski, please advise on this PR as described above. Thanks.

**Comment by byteben** [comment]
He did already, PR can be closed, info requested is already in the doc. Thanks for your help.

Kind Regards
Ben

Sent from my iPhone

On 24 Sep 2019, at 17:24, Jeff Borsecnik <notifications@github.com> wrote:

﻿

@aczechowski<https://github.com/aczechowski>, please advise on this PR as described above. Thanks.

**Pull request closed without merging**
