### PR TITLE
third-party-software-updates.md

### PR DESCRIPTION
**Pull request by sccmentor**
I submitted a pull request earlier, but not to completion I think.  I was confused around this area of the doc and felt that it needed some slight clarification on the certs. Should step 3 also mention if using a self-signed cert?

### CODE REVIEW

**Comment by GitHubber17** [comment]
@aczechowski - Would you review the proposed changes? Thanks

**Comment by aczechowski** [comment]
Thanks @sccmentor for the contribution! I'm checking with engineering team.

**Comment by renatomarson** [comment]
Hi guys, I'm new around here so excuse me if it is not the correct way to request a change.
This article apparently is not clear enough to say that port UDP  389 is needed on the "Discovery and Publishing".

We just got a CSS Premier support case where customer configured the network rules to SCCM based in this doc and the Discovery process was failing due to the lack of access to port UDP 389.
Customer was very rude in saying that this DOC does not clearly say that port UDP 389 is needed.

Can someone add this port on the required port list?

Thanks,

Renato

**Comment by aczechowski** [comment]
@sccmentor I clarified my understanding of this with engineers, and have an idea on how we can help clarify this article. There are *two* certificates involved in this process, so it might be useful to be more explicit about the two:
- Server authentication certificate for SSL on WSUS that you need to get from a public provider or generate with PKI.  
- WSUS Signing Certificate that you have to configure SCCM and WSUS to create (this is the self-signed certificate referenced further down). SCCM calls a WSUS API telling WSUS to generate this certificate. Then SCCM downloads it from WSUS and pushes it out to all clients.  

If we define these two certificates, and then use those terms throughout the process, I think that will help clarify and distinguish.

What do you think?

**Comment by sccmentor** [comment]
Yep that makes perfect sense Aaron. Clarifies the process and I understand
what is going on there now.

**Comment by aczechowski** [comment]
Great! So are you willing to make those edits? 😃 A little larger than perhaps you originally intended. I'm willing to help, because I want you to get credit for the contribution.

**Comment by sccmentor** [comment]
Sure thing Aaron. Give me a day to turn this around.

**Comment by aczechowski** [comment]
Closing this pull request as #827 is now the work in progress.

**Pull request closed without merging**
