### PR TITLE
Added links to manage Collections with PowerShell

### PR DESCRIPTION
**Pull request by ChrisKibble**
#MMS2019Docathon

@aczechowski , this should be considered for one of the most impactful changes (along with the other PowerShell updates I've made, as a whole) because teaching those reading the docs how to use PowerShell the tasks will bring more automation into SCCM and the community as a whole.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution! I'll review after the end of the contest.

#hold-off
(reviewers, please don't edit - I'll take care of it.)

**Comment by PRMerger14** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by ChrisKibble** [comment]
> Remove locale (`en-us/`) from all of the URLs

Hi @aczechowski - all set.

**Comment by aczechowski** [comment]
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 15 May) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
