### PR TITLE
Link to Configure hardware inventory

### PR DESCRIPTION
**Pull request by chnylen**
Current link goes to a 404. URL looks to have changed and I've added the correct one.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@chnylen : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @chnylen for catching the bad link. Aside from the wrong path, it also needs to change to use forward-slash `/`. Can you please change from 

`\sccm\core\clients\manage\inventory\configure-hardware-inventory`

to
`/sccm/core/clients/manage/inventory/configure-hardware-inventory`

**Comment by PRMerger7** [comment]
@chnylen : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
great, thanks!
#sign-off

**Pull request merged**
