### PR TITLE
Added details on how hw client settings are merged

### PR DESCRIPTION
**Pull request by jocasti**
### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@jocasti : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@jocasti : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
The commits in this PR were moved to the private repo in https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/3016

**Comment by jocasti** [comment]
Hi @ktoliver just had a question. I see that there are unmerged commits for this PR and a PR has been created in the private repo. Will the changes in that PR to the private repo eventually make its way back to the public repo for sccmdocs?

**Comment by aczechowski** [comment]
@jocasti the private repo is actually the primary for SCCM content. 😃 So your change will publish live tomorrow from the private repo, and then will also sync to this repo as well.

Folks with a microsoft.com account should use the private repo for changes, as there are additional tools. Continue to use the public repo for issues (unless MS confidential for some reason), but when making edits, switch to sccmdocs-pr before clicking the pencil edit icon. The workflow is otherwise the same.

**Comment by jocasti** [comment]
Got it, Thanks for clearing that up for me.

**Comment by jocasti** [comment]
Fixes https://github.com/MicrosoftDocs/SCCMdocs/issues/504.

**Pull request closed without merging**
