### PR TITLE
Shortened Title

### PR DESCRIPTION
**Pull request by ChrisKibble**
Title is so long it doesn't fit in the TOC.  There is no need to reference "with System Center Configuration Manager" here since those are the docs that are being viewed.

Submission for #MMS2019Docathon

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution! I'll review after the end of the contest.

#hold-off
(reviewers, please don't edit - I'll take care of it.)

**Comment by aczechowski** [comment]
@ChrisKibble  
The metadata title and H1 are independent of what is displayed in the left side table of contents. So what changes you have in this commit are good, but to really fix the weirdness you need to edit toc.yml. That's a bit more of an advanced change, but if you're just reducing the size of the string, it should be a simple search and modify. 

So here's the file to modify: sccm\core\TOC.yml
It's on line 721, just a matter of removing ` with` from the end of the line. 

To make the edit:
1. Go to the **Files changed** tab of the pull request.  
2. Click the pencil icon to edit the file.  
3. Make the change, and then commit it into the *same branch* (**patch-13** in this instance).  

This pull request automatically updates with your new commit.

Let me know if you have any questions.

**Comment by PRMerger6** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by ChrisKibble** [comment]
Thanks @aczechowski - the line numbers didn't match up in TOC for me, but I found what needed to be changed and made the update.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble !
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 May) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
