### PR TITLE
Update deploy-edge.md to note that the content location for the application must be empty when using the wizard to create the application. 

### PR DESCRIPTION
**Pull request by mrbodean**
Added note that the location for the content must be empty. When the specified directory is not empty the application wizard for 1910 will not proceed until it is empty or a empty location is specified.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger10** [comment]
@mrbodean : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @mestew - Could you review this pull request? Thanks.

**Comment by PRMerger7** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
@mrbodean thanks for your contribution. I made minor style and wording tweaks to it since we rarely use exclamation points in docs. 

#sign-off

**Pull request merged**
