### PR TITLE
multiple files: fix typos

### PR DESCRIPTION
**Pull request by schneiderl**
Please be aware that this pull request was automatically created using [gtf](https://github.com/schneiderl/gtf) - a typo fixing bot

You should be able to merge this with no other problems.
In case the proposed changes do not make sense, I would be glad to hear about it.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@schneiderl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @schneiderl 

Here's some feedback:
- The tool replaced "cant" in the word "significantly" with "cannot". I'll back out your revision.
  
  image

- The tool replaced two legitimate instances of "cant" with "cannot". Microsoft style is to use contractions, so I'll change these to "can't".

Then, I'll merge these typo fixes. Thanks!

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by schneiderl** [comment]
@ktoliver Thank you for the feedback. I'll be fine-tuning the tool based on that feedback.

**Pull request merged**
