### PR TITLE
Update manually-deploy-software-updates.md

### LINKED ISSUE #1144: Deadline behavior
Clarify this applies when Maintenance Window is configured. If no MW defined for the clients, this settings will not take effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7abcbb7f-bdc9-5f43-052e-5a6280961f5b
* Version Independent ID: 11a8bacd-7bde-7b90-1204-ac6324dc4e28
* Content: [Manually deploy software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manually-deploy-software-updates)
* Content Source: [sccm/sum/deploy-use/manually-deploy-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manually-deploy-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

### PR DESCRIPTION
**Pull request by MSBeatriz**
clarify deadline behavior when no MW is defined

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #1144

### CODE REVIEW

**Comment by PRMerger20** [comment]
@MSBeatriz : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@MSBeatriz : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@MSBeatriz : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@MSBeatriz @aczechowski - Please note that Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. 

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master). 

Thank you

**Comment by aczechowski** [comment]
Looks good, thanks @MSBeatriz for the contribution. #sign-off 
(NOTE: as noted, in the future please use sccmdocs-pr repo. Use the same process, just after you click **Edit** on the article, switch the URL to sccmdocs**-pr**.)

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 16 January) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
