### PR TITLE
Added Copy Application as an available task

### PR DESCRIPTION
**Pull request by ChrisKibble**
As referenced in #1464, moved Copy Applications as an available task instead of its own page.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Hi @ChrisKibble, while this is fine as-is, I think there's benefit in also adding this additional point that you had in the other PR (with a few edits of mine):

> The site creates a new application, with **-copy** appended to the name. While the site copies most of the metadata to the new application, it doesn't copy any deployments.

**Comment by PRMerger16** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Awesome, thanks @ChrisKibble, looks good 😄 
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be Tuesday, 28 May around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
