### PR TITLE
Fixed link title

### PR DESCRIPTION
**Pull request by ChrisKibble**
The title of the page linked to is “to pilot” not “to a pilot”. Changed link to match.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@aczechowski - Would you review the proposed updates? The target article uses both "Deploy to pilot" (title) and "deploy to a pilot group".

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger13** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Pull request merged**
