### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by markaldridge**
Removed unneeded slash.

### CODE REVIEW

**Comment by Brenduns** [comment]
#sign-off
@markaldridge    Thanks! This should process though the system soon.

**Comment by markaldridge** [comment]
@Brenduns not sure if you saw my comment on [f01b7d0](https://github.com/MicrosoftDocs/SCCMdocs/pull/293/commits/f01b7d017acc4a3ccdcc7b7eb093d13f82f444dd) about not getting the link to work.

**Comment by Brenduns** [comment]
@markaldridge 
Hello Mark, I'd not seen that comment. I see it now.  
After I ensure this gets processed/published, I'll sweep back to see about that link. If you submit a fix prior to that, great!  If not, I'll look for it to fix it as well.

Link Guidance: For Links, there are a couple of methods but the simplest follows.  For a link you note, use the following style to point to any location in the same repo, where after /sccm/ you just include the path from the URL you are trying to direct the reader to. So for the fallback status point subsection, use: 
 (/sccm/core/clients/deploy/plan/determine-the-site-system-roles-for-clients#determine-if-you-need-a-fallback-status-point)

 (/<relative path in the repo>/<filename without the.md>#<header-of-section>)

- That should be all lower-cased, and - replace spaces in the section header your trying to link to. 
- We don't need the bits before /sccm/ when in the same repo. 
- Unless there is reason to use a language path, even for a direct page link, we remove any language identifiers. That enables the link find and display the page in the language of the users web-browser (if available). If that language version of the topic doesn't exist, it defaults to English.

There are also older links around where we use the ../../ path to direct to the location. Those require the use of .md to identify the file.  We have moved away from using those.

**Comment by markaldridge** [comment]
@Brenduns 
I thought I tried having the link like that but it didn't work, must've been doing something wrong as it works fine now.
Thanks for explaining the link guidance. Is there a page where I can read more information about the Microsoft Docs by any chance?

**Comment by Brenduns** [comment]
#sign-off

**Comment by Brenduns** [comment]
@markaldridge  If you have not seen the contributors guide, you can find that here: https://github.com/MicrosoftDocs/Docs/blob/master/ContributorGuide/index.md 
It's not too extensive, but its what's available at this time.

**Pull request merged**
