### PR TITLE
Update manage-office-365-proplus-updates.md

### PR DESCRIPTION
**Pull request by davidpaMSFT**
This issue doesn't occur only "When you install an operating system where Office 365 is already installed in the image", it can also occur when Office 365 ProPlus is installed during OSD task sequence, prior to installing updates.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger17** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by davidpaMSFT** [comment]
The title of this section should be changes as well to align with this change.

**Comment by davidpaMSFT** [comment]
In the "Deploy Office 365 updates" section this should be added to the first paragraph: "For instructions on how to do this during OSD task sequence, see <link to the task sequence section>".

**Comment by aczechowski** [comment]
Thanks @davidpaMSFT for the contribution. I agree those additional changes are beneficial. Can you make them? I also suggest adding more detail to the paragraph you originally edited as to the two OSD scenarios. Or could just generally say, any OSD scenario. 

To make the edits:
1. Go to the **Files changed** tab of the pull request.  
2. Click the pencil icon to edit the file.  
3. Make the change, and then commit it into the *same branch*.  

This pull request automatically updates with your new commit.

Let me know if you have any questions.

**Comment by PRMerger12** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by davidpaMSFT** [comment]
I completed the changes. "Method 2" in the "task sequence section" is new content.

**Comment by aczechowski** [comment]
Thanks @davidpaMSFT for the additional info. The only blocking issue is "en-us/" in the URLs. Can you please remove them? Use the following format: `https://docs.microsoft.com/sccm/...`

**Comment by PRMerger10** [comment]
@davidpaMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by davidpaMSFT** [comment]
Done.

**Comment by aczechowski** [comment]
Thanks @davidpaMSFT, looks good. #sign-off 

*Once merged*, this should be live with the next daily publishing process. We *just* missed for today, so right now that *should* be tomorrow (Wednesday, 30 January) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
