### PR TITLE
Added Office Insider CDN Reference

### LINKED ISSUE #1580: What is CDNBaseUrl for Insider (Fast) ?
When using Insider (Fast) , what is CDNBaseUrl ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#change-the-update-channel-after-you-enable-office-365-clients-to-receive-updates-from-configuration-manager)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #1580

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble - I need to check on this first. We have some larger plans for this article...

**Comment by ChrisKibble** [comment]
Understood, thanks @aczechowski and let me know if there is anything I can do to help.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for submitting this edit, but I'm going to decline it. I'll explain more why when I comment on the issue in a minute

**Pull request closed without merging**
