### PR TITLE
Sorted Views and Added 2 new view

### PR DESCRIPTION
**Pull request by Garthmj**
-sorted views
- added v_GS_SYSTEMBOOTDATA
- added v_GS_SYSTEMBOOTSUMMARY
- added sample query for Aaron to provide feedback on style.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
I'm going to close and reopen to see if that resets things...

**Comment by PRMerger17** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by adunndevster** [comment]
Looking into why there are so many thank you messages.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@aczechowski : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @Garthmj for the edit, and sorry for the noisy automation. We discovered a bug based on an issue with the metadata (which I just fixed for this article). Your changes look good to me, thanks! #sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Tuesday, 4 June) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
