### PR TITLE
Noted that CCMSETUP still runs on clients in the exclusion collection.

### LINKED ISSUE #967: Futher documentation needed
It is worth noting in the documentation that in the upgrade mechanism, a new ccmsetup.exe file is downloaded and executed on ALL machines, even those who are part of the exclusion list. It's the ccmsetup.exe that determines if a machine should be upgraded. This is worth noting this as by using the auto-upgrade we are now touching systems when we're not intending to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7000ae26-9f15-9644-55b9-e5db68c47ff2
* Version Independent ID: 8a672552-6e90-cd91-419c-ba6a5292fabf
* Content: [Upgrade clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers)
* Content Source: [sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #967.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved merge conflict (two blank lines); merging.

**Pull request merged**
