### PR TITLE
Update sms_packagebaseclass-server-wmi-class.md

### PR DESCRIPTION
**Pull request by Skatterbrainz**
Changed the property names to use the triple-pound formatting tag (heading 3)

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Skatterbrainz : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
This looks good, thanks @Skatterbrainz for the contribution! 😃 
Fixes #1081 
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *could* be today (Monday, 17 December) around 11:00 Pacific time. No further action needed from you.

**Comment by jocasti** [comment]
Fixes https://github.com/MicrosoftDocs/SCCMdocs/issues/1081

**Comment by Skatterbrainz** [comment]
Thanks!

**Pull request merged**
