### PR TITLE
Updated to Microsoft Product Lifecycle.

### PR DESCRIPTION
**Pull request by xstaindx**
Currently, according to Product Lifecycle Microsoft CSS only provides product support for the following SQL Versions that are listed as  compatible with SCCM Current Branch:

SQL 2012 SP4
SQL 2014 SP2, SP3
SQL 2016 SP2
SQL 2017

The versions were listed on the page that are no longer supported by Microsoft according to Lifecycle. 

SQL Server 2014 SP1: Standard, Enterprise, Express (Support Ended: 2017/10/10)
SQL Server 2012 SP3: Standard, Enterprise, Express (Support Ended: 2018/01/09)
SQL Server 2016 RTM: Standard, Enterprise, Express (Support Ended: 2018/01/09)
SQL Server 2016 SP1: Standard, Enterprise, Express (Support Ended: 2019/07/09)
SQL Server 2008 R2 SP3: Standard, Enterprise, Express (Support Ended: 2019/07/09)

I know this may require testing from SCCM PG but this is accurate to product lifecycle.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@xstaindx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
@mestew see MicrosoftDocs\SCCMDocs-pr#3691, this contribution might fix that (or at least part of it?)

**Comment by PRMerger8** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
@xstaindx Thanks for the contribution! 
I did have to edit your PR a bit to fix a few merge conflicts I knew were on their way... especially since I caused them =) 
I also wanted you to get credit for your contribution to docs on this page and not just close your PR. Thanks so much for the help!

**Pull request merged**
