### PR TITLE
Update sql-server-alwayson-for-a-highly-available-site-database.md

### PR DESCRIPTION
**Pull request by russrimm**
### Summarize the change in the pull request title

One typo and one change for drop-down menu option

### CODE REVIEW

**Comment by PRMerger19** [comment]
@russrimm : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @russrimm for the contribution! I'm not familiar with the SQL configurations, so I'll trust that you're right on the setting name 😃 
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Friday, 21 December) around 11:00 Pacific time. No further action needed from you.

**Comment by aczechowski** [comment]
Fixes #1107

**Comment by Jak-MS** [comment]
@russrimm ,

Please note that Microsoft employees should make content contributions through the private repository so the content can be staged and validated by the current validation rules.

Read about [working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.

Thank you.

**Pull request merged**
