### PR TITLE
Update configure-role-based-administration.md

### PR DESCRIPTION
**Pull request by NonSecwitter**
updated to reflect radio button options in SCCM dialogue

### CODE REVIEW

**Comment by PRMerger17** [comment]
@NonSecwitter : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @NonSecwitter for the contribution, good catch! By my count, there are actually 11 instances of that string on the page. Would you mind changing them all to be consistent? (If you're using the GitHub.com editor, CTRL-F opens a search box in the browser editor.)

Also, do you want to fix the string on the other option in that dialog as well? :) Instead of "All securable objects that are relevant to their associated security roles", it's now "All instances of the objects that are related to the assigned security roles."

**Comment by aczechowski** [comment]
Hi @NonSecwitter, are you able to make these other changes? If not, please let me know and I'll include the changes myself (but still accepting your contribution). If I don't hear from you by Tuesday, 14 August, I'll just do it.

**Comment by aczechowski** [comment]
Huh...well there's a new one. Sorry, I didn't realize that *my* commit will trigger the license agreement requirement for you. Well, a good thing to have in place if you ever feel the need for a larger contribution! 

@NonSecwitter please sign the Contributor License Agreement so that we can continue with this.

**Comment by aczechowski** [comment]
I haven't heard back from @NonSecwitter. Since his changes were minor (and did not originally trigger a CLA check), I'm just going to merge this pull request with my added commits.

**Pull request merged**
