### PR TITLE
Created new files for missing IProgressUI methods

### PR DESCRIPTION
**Pull request by AdamGrossTX**
Docs were missing for several IProgressUI methods

### CODE REVIEW

**Comment by PRMerger15** [comment]
@AdamGrossTX : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by AdamGrossTX** [comment]
Please also review #1314. It was auto closed since it is a new file.

**Comment by dougeby** [comment]
@aczechowski, can you take a look at this?

**Comment by Jak-MS** [comment]
@aczechowski - we'll need to move this to the private repo if you want to keep this content. this to take advantage of the automatic validation and staging tools.

**Comment by aczechowski** [comment]
I have a side thread with @AdamGrossTX on this. We don't need this pull request anymore, so I'm closing it.

**Pull request closed without merging**
