### PR TITLE
Update recommended-hardware.md

### PR DESCRIPTION
**Pull request by davidpaMSFT**
The table in the "Site server" section doesn't apply only to "Stand-alone primary site", therefore either the title for the first column should be removed or the table should be split in three: 1. Stand-alone primary site (rows 1-3), 2. Hierarchy with central administration site (rows 4-9), 3. Secondary site (row 10).

### CODE REVIEW

**Comment by arob98** [comment]
@Brenduns For your review.

**Comment by Brenduns** [comment]
@davidpaMSFT  
Hello David. Good catch on the column header.  That was a remnant from a former topic structure, which was not corrected.   However, we should not have a blank column header.  

Before we can accept this, can you modify your PR to add the following as that first column header:    "Site configuration"

Thanks,
Brent

**Comment by davidpaMSFT** [comment]
Done.

**Comment by Brenduns** [comment]
#sign-off

Thanks for the edit!

**Pull request merged**
