### PR TITLE
fix: MD046/code-block-style

### PR DESCRIPTION
**Pull request by nschonni**
Use explicit code fences. Some implict ones appear unintentional

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @aczechowski - Could you review this PR? I can verify some of the updates, but I can't tell whether all of the sections now in code blocks are meant to be code. Thanks.

**Comment by mestew** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@mestew: I'm sorry - only the author of this article, @aczechowski, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger7** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Pull request merged**
