### PR TITLE
Updated supported versions of SQL following MVP DL thread

### PR DESCRIPTION
**Pull request by peteregerton**
I removed support statements in this doc for SQL server 2012 (all SPs), 2014 SP1 and SQL Express versions before 2017. I also amended the statement around SQL 2008 R2 to be inclusive of all earlier SQL versions. This is following an MVP DL thread with Aaron Czechowski and Lamar Damata. I will also amend the corresponding page which lists deprecated versions.
https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server#deprecated-support-for-sql-server-versions-as-a-site-database

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by aczechowski** [comment]
Thanks @peteregerton for the contribution. @mestew will help with this one. 

(For MicrosoftDocs/SCCMDocs-pr#3691, email thread "Docs - SQL Supported versions")

**Comment by aczechowski** [comment]
Oh, and thank you @peteregerton for making your *first* contribution to SCCMDocs! 😃

**Comment by PRMerger17** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
@peteregerton
Thanks for the contribution!
I did have to edit your PR a bit to fix a few merge conflicts I knew were on their way... especially since I caused them =)
I also wanted you to get credit for your contribution to docs on this page and not just close your PR. Thanks so much for the help!

**Pull request merged**
