### PR TITLE
Using Custom path with the Download Package Content step

### PR DESCRIPTION
**Pull request by PotentEngineer**
Added two clarifications around a Custom Path for the Download Package Content step.

- Content is downloaded to the task sequence package cache then moved to the custom path

- The package ID is appended to the custom path

### CODE REVIEW

**Comment by aczechowski** [comment]
@PotentEngineer I have another edit in the works for this article. Once that's complete, I'll review this.

**Comment by aczechowski** [comment]
Verifying with engineering team

**Comment by aczechowski** [comment]
Hi Daniel @PotentEngineer - thanks for making this contribution! Some feedback before we publish. Instead of a note I think we can just make this the description of the option. Use active voice whenever possible. Instead of "the package is moved" say "the TS engine moves the package." And let's clarify what is appended. Here's my suggestion, please adjust as desired and re-commit (which will automatically update the pull request). Let me know if you have any questions!

 -   **Custom path**: With this option the task sequence engine first downloads the package to the task sequence working directory, and then moves it to this path you specify. The task sequence engine appends the path with the package ID.

**Comment by PotentEngineer** [comment]
Thanks for the guidance Aaron. The changes are committed.

**Comment by aczechowski** [comment]
Looks good. #sign-off
@arob98 or @mtillman can you please merge?

**Comment by arob98** [comment]
@aczechowski @PotentEngineer - Looks like there is a merge conflict. Can you resolve the conflict and let me know when it's ready to merge?

**Comment by PotentEngineer** [comment]
Closing and reopening per Aaron.

**Pull request closed without merging**
