### PR TITLE
Update optimize-windows-10-update-delivery.md

### PR DESCRIPTION
**Pull request by davguent**
The reference "all windows updates" is causing confusion for IT Pros as they assume this includes Office which is not the case.  Adding line of clarity on how to unwind Office integration with SCCM to use DO.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@davguent : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
