### PR TITLE
Update manage-windows-as-a-service.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Removed surplus words from a sentence.
General tidying up of markdown.
Several smaller changes, like correcting number of spaces between words, etc.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@baardhermansen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off

**Comment by ktoliver** [comment]
We'll move this commit to the private repo so we can verify the formatting changes on staging before merging the PR. We'll post the new PR number here shortly, and then close this PR. The original contributor will continue to be associated with the updates in the PR. Thanks.

**Comment by mestew** [comment]
@ktoliver Sounds like a good plan to me. Thanks! I double checked the formatting in VSCode's preview as I was reviewing it, but would love another set of eyes on it.

**Comment by ktoliver** [comment]
The updates look good on staging. Instead of closing this PR, I'll close the private repo PR as a test PR, and merge this one. Thanks.

**Pull request merged**
