### PR TITLE
Reviewed for accuracy

### PR DESCRIPTION
**Pull request by ChrisKibble**
Removed pipe character that wasn't meant to be included and reviewed for accuracy.

#MMS2019Docathon

### CODE REVIEW

**Comment by PRMerger16** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution! I'll review after the end of the contest. (and deal with the merge conflict)

#hold-off
(reviewers, please don't edit - I'll take care of it.)

**Comment by PRMerger13** [comment]
@aczechowski : Thanks for your contribution! The author, @mestew, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Fixed merge conflict
#sign-off

**Comment by PRMerger14** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mestew** [comment]
#sign-off

**Pull request merged**
