### PR TITLE
Correct linked URLs and poor wording

### LINKED ISSUE #2249: KeepActivation Links to old documentation
The URL for Task Sequence Variable documentation links to the docs for ConfigMgr 2007 instead of Current Branch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e497ffc-841c-8d38-b30f-3d19af5f24ce
* Version Independent ID: c6d5168d-cb3d-f9c1-d908-4e61532da994
* Content: [SMS_TaskSequence_PrepareOSAction Class - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class#properties)
* Content Source: [sccm/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

### PR DESCRIPTION
**Pull request by merlinfrombelgium**
Correct linked URLs from ConfigMgr 2007 documentation to Current Branch.
Fix poor wording on KeepActivation description.

Fixes #2249 #2248

### CODE REVIEW

**Comment by PRMerger7** [comment]
@merlinfrombelgium : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@aczechowski If the proposed changes are approved, I can remove the locales from the links before merging.

**Comment by aczechowski** [comment]
#sign-off 
Thanks @ktoliver for the offer and assistance!

**Comment by merlinfrombelgium** [comment]
> Thanks @merlinfrombelgium, good stuff! 😄
> 
> In the future, don't include locales (`en-us`) in the URL, so we keep the content language neutral. In our repository, for any link internal to our content, we generally try to standardize on root relative links: `/configmgr/osd/understand/task-sequence-variables`. That's mainly to make it easier for the community to add links. For any link external to configmgr content, use the full URL (without locale).

Gotcha! Should have known that from a previous time 😳

**Comment by PRMerger14** [comment]
@ShannonLeavitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
