### PR TITLE
rights note for Reporting services point account

### PR DESCRIPTION
**Pull request by ChadSimmons**
Added note to Reporting services point account that permissions are automatically granted.

This is useful to avoid confusion with admins expecting that they must manually grant db access.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ChadSimmons : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 19 February) around 11:00 Pacific time. No further action needed from you.

**Comment by ChadSimmons** [comment]
@aczechowski or @ktoliver I see the update is live (YEAH!) but the date on the article didn't change.  Is it supposed to?

**Comment by ktoliver** [comment]
Hi @ChadSimmons - No. Per the Microsoft Docs internal contributor guide, the `ms.date` metadata attribute (which dictates the date to display) "indicates the last time the article was substantially edited or guaranteed fresh." So, it's changed manually when an update meets that criteria, and not with every commit that's merged.

**Pull request merged**
