### PR TITLE
Update create-custom-reports-using-sql-server-views.md

### PR DESCRIPTION
**Pull request by raghuke**
### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@aczechowski : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Sorry @raghuke for the noisy automation. We discovered a bug because of how the metadata is structured. 

Your change looks good, #sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Tuesday, 4 June) around 11:00 Pacific time. No further action needed from you.

Reminder, as a Microsoft FTE, in the future, please use sccmdocs-pr repo. Use the same process, just after you click Edit on the article, add **-pr** to the URL for sccmdocs-pr.

**Comment by PRMerger13** [comment]
@Jak-MS : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Pull request merged**
