### PR TITLE
Update troubleshooting.md to remove incorrect/misleading steps

### PR DESCRIPTION
**Pull request by ameltzerMSFT**
Remove unneeded/incorrect steps for enabling verbose logging

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ameltzerMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ameltzerMSFT for the contribution. @iceorbital made a [change four days ago](https://github.com/MicrosoftDocs/SCCMdocs/commit/f716edc0e330c03ea44ebdc74d40647670ceda70#diff-2d8e663c060aa2b4ed3fd2f1153a2eb6) to change the registry value from **LogLevel** to **LoggingLevel**. This has caused a merge conflict, which I can fix but need to know which one is correct. I want to accept your change otherwise to remove the additional steps.

**Comment by ameltzerMSFT** [comment]
LoggingLevel is correct

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 3 July) around 11:00 Pacific time. No further action needed from you.

As a Microsoft FTE, in the future, please use sccmdocs-pr repo. Use the same process, just after you click Edit on the article, add **-pr** to the URL for sccmdocs-pr.

**Pull request merged**
