### PR TITLE
Update manage-apps-from-the-windows-store-for-business.md

### PR DESCRIPTION
**Pull request by AmandaAZ**
add a reference to a kb article

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by AmandaAZ** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@AmandaAZ: I'm sorry - only the author of this article, @aczechowski, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@AmandaAZ : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @AmandaAZ, great addition!
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 May) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
