### PR TITLE
Changed a typo from "hours" where UI is in "minutes"

### PR DESCRIPTION
**Pull request by peteregerton**
The UI for the setting "Specify the snooze duration for computer restart countdown notifications" in Client Settings > Computer Restart is actually quoted in minutes in the UI. The docs said hours.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger12** [comment]
@peteregerton : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @peteregerton 
I'll let @mestew review and signoff
Do you want to submit a change for the client settings article as well? https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#computer-restart As well as the label, the default is "240 minutes"

**Comment by PRMerger15** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
@peteregerton it was very nice of you to call that oops a "typo" =) 
I also added a commit to this PR to change hours -> minutes in the new device restart notification article too.

**Comment by PRMerger15** [comment]
You can only sign off in the main PR conversation, not in review comments. In general, the creator of the PR should sign off, not the tech reviewer.

**Comment by mestew** [comment]
#sign-off ...since it doesn't seem to work when I take a shortcut and put it in my review comments.

**Pull request merged**
