### PR TITLE
Added into on public wildcard certificate info

### PR DESCRIPTION
**Pull request by jshackelford9375**
#mms2019docathon Added info on publicwildcard cert and use in CMG

### CODE REVIEW

**Comment by PRMerger10** [comment]
@jshackelford9375 : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @jshackelford9375 for the contribution! And for making your first contribution to SCCMDocs. 😄 

In this instance, I want to review with the feature team. I'll review after the end of the contest, but will still consider this change for the contest.

#hold-off
(reviewers, please don't edit - I'll take care of it.)

**Comment by jshackelford9375** [comment]
Thanks for the feedback. I was very confused on that step myself and had several other people take a look as well with the same result.

**Comment by aczechowski** [comment]
@jshackelford9375 I had a chat with the engineering team.

1. For the first one, what we expose in Certificates node is just the public key. Why would you want to export it?
2. I'm not sure about the reference to CMG in this context? It's not really relevant to E-HTTP.

Can you provide some more information to help clarify?

**Comment by aczechowski** [comment]
@jshackelford9375 bumping this if you can answer my previous questions. Otherwise I'll close this pull request.

**Pull request closed without merging**
