### PR TITLE
SQL Server Service Broker is Required

### LINKED ISSUE #452: SQL broker usage documentation
It is well known and documented that the sql broker is used for site replication
(https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-transfers-between-sites - To replicate data between sites, Configuration Manager uses its own database replication service. The database replication service uses SQL Server change tracking to monitor the local site database for changes, and then replicates the changes to other sites by using SQL Server Service Broker (SSB). By default, this process uses TCP/IP port 4022.)

however, it is not known if SQL Broker is required in a single std primary site. as per conversation with PGs, it is required for some functions like BGB, so this information should be documented.

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #452

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution!
#sign-off

**Comment by PRMerger16** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mestew** [comment]
#sign-off

**Comment by aczechowski** [comment]
Blurg! 🤕  I keep forgetting the automation in this repo requires the tagged author to signoff...hang on

**Comment by mestew** [comment]
@aczechowski Gets me every time too =)

**Pull request merged**
