### PR TITLE
Update upgrade-on-premises-infrastructure.md

### PR DESCRIPTION
**Pull request by bryandam**
According to Johan, a site reset is required after in-place upgrading the primary site server's OS.
https://twitter.com/ip1/status/951431016811347968

### CODE REVIEW

**Comment by bryandam** [comment]
According to Johan, a site reset is required after in-place upgrading the primary site server's OS.
https://twitter.com/ip1/status/951431016811347968

**Comment by aczechowski** [comment]
We're validating this with engineering team, standby...

**Comment by aczechowski** [comment]
@bryandam, I'm finally getting back to this, am going to merge it. :) Adding additional context as to why it took so long. Basically, there was some debate. Technically, site reset is not required after upgrading the OS underneath the primary site server. If something goes awry during the OS upgrade, then we should investigate that issue with the OS. On the other hand, site reset is intended to be a safe catch-all for potential or real issues. So it should be harmless to reset the site after OS upgrade. Thus, let's document it as general guidance.

**Comment by bryandam** [comment]
Thanks again Aaron!

**Pull request merged**
