### PR TITLE
Update deploy-edge.md

### PR DESCRIPTION
**Pull request by SweJorgen**
Added Allsigned and a section that the script turns off automatic updates.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@SweJorgen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
@SweJorgen I'm just waiting on confirmation from PG. I suspect you are right, just need to verify.

**Comment by PRMerger16** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
@SweJorgen I double checked with one of the devs. The script is signed so the AllSigned execution policy should work so long as MS is trusted publisher. So I did remove that from the proposed changes. 

I can totally see in the ps1 script that we do set HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate\Update<channel> to 0. Looks like if for some reason this already exists and is set to 1, install fails with "AutoUpdate value set incorrectly" (my PSH reading is just "ok" so I might be wrong) . Let me know if you run across that while you're testing and if you think it's worth mentioning or not. To me, it just seems like general app install troubleshooting, but let me know if you disagree.

**Comment by PRMerger6** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off

**Pull request merged**
