### PR TITLE
Added link to sms_advertisement class

### PR DESCRIPTION
**Pull request by ramseygr**
I created a link on SMS_Advertisement to link to the  url below.   SMS_Advertisement contains the info for advertisement flags.
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class.md

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

@Article_Author please review (look at the `author` metadata tag)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ramseygr : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ramseygr for your contribution! This looks good, #sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be today (Monday, 8 October) around 11:00 Pacific time.

**Comment by ramseygr** [comment]
Hi - I noticed that the link isn't working as expected.

it's linking here:
https://docs.microsoft.com/en-us/sccm/reference/core/servers/configure/sms_advertisement-server-wmi-class
but I receive a 404 error when I try to go there.

I do see the info here:

https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class

 please let me know if I should submit another pull request.

Thanks,

Greg

**Comment by aczechowski** [comment]
Thanks @ramseygr, I noticed that as well during the publishing process. I already submitted a fix that will publish tomorrow. (The private repository that I primarily use has some additional tools to help check for those sorts of things.) But your contribution still counts! 😃

**Comment by ramseygr** [comment]
ok-thanks. I still need remediation training :).

**Pull request merged**
