### PR TITLE
Update enable-data-sharing.md

### PR DESCRIPTION
**Pull request by ameltzerMSFT**
Add additional microservice URL

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ameltzerMSFT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Jak-MS : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Jak-MS : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by ameltzerMSFT** [comment]
> @Jak-MS : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

There's a bunch of additional incorrect uses of the BR tag. I was just following convention here. :)

image

**Comment by Jak-MS** [comment]
@ameltzerMSFT - oh, yeah... i wasn't specifically correcting that ... I was trying to get the URL to fit on one line inside the table... and figured i'd update the \<br> code while I was there... it's true that the other instances should ideally also be fixed, but they render okay so it's low priority. thanks... (we'll see what @aczechowski  says about the addition...)

**Comment by aczechowski** [comment]
@ameltzerMSFT, I just approved a similar change from @iceorbital in MicrosoftDocs/SCCMDocs-pr#3485. Although he replaced the URL instead of adding. Can ya'll let me know how you want to handle it? (Keeping in mind that *this* conversation is in the public repository 😄)

**Comment by ameltzerMSFT** [comment]
My changes added an additional URL to the list that was previously missing

**Comment by aczechowski** [comment]
Based on email response from Bryan, I'm closing this PR unmerged.

**Pull request closed without merging**
