### PR TITLE
Update list-of-reports.md

### PR DESCRIPTION
**Pull request by Garthmj**
added report counts to all sections

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @Garthmj, generally looks ok. Per [Microsoft Style](https://docs.microsoft.com/style-guide/numbers), can you please adjust to spell out whole numbers from zero through nine, and use numerals for 10 or greater.

**Comment by Garthmj** [comment]
Np... that would have been easier.





Regards,
Garth Jones
Tel: 613-627-4801 x168

[cid:image001.jpg@01D2D4A2.6417FD90]<https://www.enhansoft.com/>
Configuration Manager/SCCM Reporting<https://www.enhansoft.com/>

**Comment by PRMerger7** [comment]
@Garthmj : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Looks great, thanks @Garthmj! 
#sign-off

**Pull request merged**
