### PR TITLE
Update fundamentals-of-security.md

### PR DESCRIPTION
**Pull request by NonSecwitter**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@NonSecwitter : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @NonSecwitter for submitting the contribution, but I'm not clear on what changed? I scanned the diff under the Files tab, but it looks to be identical. Can you please clarify what you changed, and for what purpose?

**Comment by aczechowski** [comment]
Hi @NonSecwitter. Please let me know what was the intent of this change. As I said, it doesn't appear as if there is any delta. Otherwise I'll close this pull request on or around Tuesday, 14 August.

**Comment by ChrisKibble** [comment]
@aczechowski - the original file has the text 

> Security scopes **the** group specific instances of objects that an administrative user is responsible to manage 

The update from @NonSecwitter removes the word "the".

**Pull request merged**
