### PR TITLE
Removed a Comma

### PR DESCRIPTION
**Pull request by JordanTheITGuy**
Removed a Comma and added word clarity around the SUP not running cleanup on secondary site servers.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger12** [comment]
@JordanTheITGuy : Thanks for your contribution! The author, @mestew, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@JordanTheITGuy : Thanks for your contribution! The author, @mestew, has been notified to review your proposed change.

**Comment by JordanTheITGuy** [comment]
Done! Updated the file to use the contraction instead.

**Comment by mestew** [comment]
#sign-off

**Pull request merged**
