### PR TITLE
Update integrate-windows-update-for-business-windows-10.md

### PR DESCRIPTION
**Pull request by theredrabitt**
Corrected Feature Update deferral period from 180 to 365 days (as per Config Manager current branch verification & numerous other MS Docs sources)
Corrected point #5 which appears to have been copied and pasted incorrectly and contained references to Feature Updates (repeated) instead of Quality Updates

### CODE REVIEW

**Comment by aczechowski** [comment]
@theredrabitt just making sure you closed this on purpose. If you want your changes to be reviewed and merged into the content, reopen the pull request. Otherwise it's in a closed state, and not merged.

**Comment by theredrabitt** [comment]
LOL - Thanks Aaron.
Can you tell I'm a first time user 😣
Re-opened now...

**Comment by aczechowski** [comment]
No prob, that's why I checked! Happy to help, thanks for taking the time to submit a contribution. 😄 Let me confirm the technical details - stay tuned.

**Comment by aczechowski** [comment]
Ok cool, just wanted to double-check the console behavior. #TrustButVerify! :)
This looks good. 
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be today (Friday, 7 September) around 11:00 Pacific time.
#sign-off

**Pull request merged**
