### PR TITLE
Added checklist link for 1710 update

### PR DESCRIPTION
**Pull request by Mhudson97**
#MVPHackADoc

### CODE REVIEW

**Comment by Mhudson97** [comment]
#MVPHackADoc

**Comment by aczechowski** [comment]
@Mhudson97 this one? It's closed :(

**Comment by Mhudson97** [comment]
Ok thank you. Yes this one.


Matthew Hudson
Schlumberger
Senior Systems Engineer

Sent from my iPhone

On Mar 9, 2018, at 12:27 PM, Aaron Czechowski <notifications@github.com<mailto:notifications@github.com>> wrote:


@Mhudson97<https://github.com/mhudson97> this one? It's closed :(

**Comment by aczechowski** [comment]
Ideally we'd leave all currently supported versions in the list. But we'll be updating this again in a few days anyway :)

**Comment by Mhudson97** [comment]
Yup. This is the one I know I made the link change.


Matthew Hudson
Schlumberger
Senior Systems Engineer

Sent from my iPhone

On Mar 9, 2018, at 1:21 PM, Aaron Czechowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #427<https://github.com/MicrosoftDocs/SCCMdocs/pull/427>.

**Pull request merged**
