### PR TITLE
Detail OS applicability of registry values CommercialId and AllowTelemetry

### PR DESCRIPTION
**Pull request by juanandmsft**
### Summarize the change in the pull request title

Specify OS applicability for both CommercialId and AllowTelemetry as rest of values in table.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@juanandmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@juanandmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@juanandmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 23 October) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
