### PR TITLE
doc for Resource Explorer Classes.  fixes #1457

### LINKED ISSUE #1457: Missing page for System Boot Summary data
Please create a new page documenting what the data in Resource Explorer - System Boot Summary stands for and represents.

(admin edit - add article metadata to create link to target)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d67116-14b6-bec6-01ca-1e4d40ec3f09
* Version Independent ID: 8a7b5a36-18fd-6392-d60c-da717a26b004
* Content: [How to use Resource Explorer - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/inventory/use-resource-explorer-to-view-hardware-inventory)
* Content Source: [sccm/core/clients/manage/inventory/use-resource-explorer-to-view-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/use-resource-explorer-to-view-hardware-inventory.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

### PR DESCRIPTION
**Pull request by AdamGrossTX**
Import
### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by Jak-MS** [comment]
@aczechowski @mestew - can you take a look and review this? we'll have to move it over to the private repo if it looks good. let us know if you'd like help with that. thanks.

**Comment by aczechowski** [comment]
#sign-off 

I made a tweak to the metadata, but otherwise I think this is ok to publish.

**Comment by PRMerger6** [comment]
@aczechowski: I'm sorry - only the author of this article, @aaroncz, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
it helps if i use the right username 🤣 
#sign-off

**Comment by Jak-MS** [comment]
thanks @aczechowski - we'll need to move these commits to the private repo and merge from there after it passes validation and staging checks. 

@AdamGrossTX - we'll comment here when the content is moved and merged. thanks.

**Comment by aczechowski** [comment]
The private PR merged, the article should publish tomorrow (Wednesday, 4 December). 
Thanks @AdamGrossTX for your contribution 😉 
#please-close
(and we can close #1457 as well)

**Pull request closed without merging**
