### PR TITLE
Corrected capitalization of Internet

### PR DESCRIPTION
**Pull request by ChrisKibble**
#MMS2019Docathon submission.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by jborsecnik** [comment]
Microsoft recently changed it's style to lower case "internet," as part of a larger tend. But thanks for your input.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble. For future reference: https://docs.microsoft.com/style-guide/a-z-word-list-term-collections/i/internet-intranet-extranet
p.s. to be clear, I'm not going to count this PR towards the contest 😢

**Comment by ChrisKibble** [comment]
Understood and thanks for the style guide!

**Pull request closed without merging**
