### PR TITLE
Reviewed for Accuracy and Fixed Incorrect Brackets

### PR DESCRIPTION
**Pull request by ChrisKibble**
Brackets were included around Application Deployment as if someone was eventually going to create a markdown link but didn't.  Also reviewed for accuracy and updated article date.

#MMS2019Docathon submission

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by jborsecnik** [comment]
Verified correction.

**Comment by jborsecnik** [comment]
The fix is apparently correct. Should the date be changed as marked?

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution!
#sign-off 
*Once merged*, this should be live with the next daily publishing process. Right now that *could* be today (Wednesday, 8 May) around 11:00 Pacific time. No further action needed from you.

**Pull request merged**
