### PR TITLE
chore: Remove manual @ for PR template

### PR DESCRIPTION
**Pull request by nschonni**
The PR bot is setup in the repo so this shouldn't be needed anymore

### CODE REVIEW

**Comment by aczechowski** [comment]
Thanks @nschonni. Good point. 😃 (And realistically most contributors don't use the template anyway! 😭)
#sign-off

**Comment by nschonni** [comment]
PS: Since files like test don't get understood by the PR Bot, it might make sense to use a CODEOWNERS file for these files at the root https://help.github.com/articles/about-codeowners/

**Comment by aczechowski** [comment]
Thanks @nschonni - right now I'm the only one that manages this repo, and am watching for all activity. So the bot is a bit redundant for me. 😄 
p.s. there are some issues with things today, so I'm going to wait and see what happens when those clear. Worst case I'll just manually merge these PRs. Thanks for your cleanup contributions!

**Comment by nschonni** [comment]
Ah, right, the Webhooks are still queued right now https://status.github.com/messages

**Comment by PRMerger6** [comment]
@aczechowski: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
