### PR TITLE
Update site-server-high-availability.md

### PR DESCRIPTION
**Pull request by SQLSteveT**
### securityadmin** security role NOT needed

Describe your change, specifically *why* you think it's needed.

Once the Sysadmin role is added, the machine account has ALL the permissions needed to complete the operation.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@SQLSteveT : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @SQLSteveT for the feedback. I'll strike up an email thread with the PM who specifically included that in recent notes. 
#hold-off

**Comment by aczechowski** [comment]
Still waiting on response from engineering team

**Comment by aczechowski** [comment]
Hey @SQLSteveT, sorry for the long delay. I finally got confirmation from engineering that contrary to some previously shared information, securityadmin isn't needed. 
#sign-off 

FYI, due to a publishing freeze this week, this change should go live on Monday, 6 May. No further action needed from you.

**Comment by SQLSteveT** [comment]
Hi Aaron,

Thanks for the confirmation. Happened to look at this same page today, as we ready for MMS.

-Steve

**Comment by PRMerger12** [comment]
@SQLSteveT: I'm sorry - only the author of this article, @aczechowski, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
