### PR TITLE
Changed "managed virtual machines" to "managed systems" in Cloud Prot…

### PR DESCRIPTION
**Pull request by jason4tw**
…ection Service description.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jason4tw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Just checking whether the automation allows signoff from non-authors...
#sign-off

**Comment by PRMerger6** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
Nope, ok. This is a super simple change, but @mestew will need to do the honors. 😄

**Comment by mestew** [comment]
@aczechowski should I trust you and @jason4tw? hrmmm I need to think about this one.   ;-P 
#sign-off

**Pull request merged**
