### PR TITLE
Adds a link and summary of Administrator's Guide

### PR DESCRIPTION
**Pull request by 1RedOne**
### Summarize the change in the pull request title
Add's a helpful link to the very useful and little known administrator's guide to this document about the same sorts of troubleshooting.  Later on, one might decide to merge the docs somehow, but this at least links the material for today's consumption.
🎃 🎃 

Fixes #Issue_Number (if necessary)
Related to #1782

### CODE REVIEW

**Comment by PRMerger6** [comment]
@1RedOne : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @1RedOne for the contribution! Sorry for the slow response, I was out of the office for a few days. I'm also checking with someone that's been doing some work in this area. Stay tuned...

**Comment by aczechowski** [comment]
Hi @1RedOne, I hate to do this, but I'm going to decline this change. 😢 
The reason, and the good news, is that with work that's in progress that KB should be irrelevant. So stay tuned for more updates in this area soon! 😉

**Comment by 1RedOne** [comment]
No worries.

**Pull request closed without merging**
