### PR TITLE
Update supported OS of CmRcViewer.exe

### PR DESCRIPTION
**Pull request by yuhonda**
Customer found that CmRcViewer.exe does not works on Win2008. This is by design but there is no mention in official docs and please add this limitation in this doc.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@yuhonda : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @yushonda - Would you take a moment to sign the CLA? After the CLA is signed, someone will review your changes. Thanks!

**Comment by mestew** [comment]
Once @yuhonda (who's an epic EE for us) signs CLA, I am good with approving the changes to the article.

**Comment by PRMerger19** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
