### PR TITLE
Updating the pre-requisites

### PR DESCRIPTION
**Pull request by raghuke**
Adding Service Connection Point role, which was missed from pre-requisites for supporting modern windows release cycle.

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

### CODE REVIEW

**Comment by PRMerger15** [comment]
@raghuke : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Hi @raghuke, per our email, do you also want to note that it needs to be online to get updates to the dashboard? 

To make the edit:
1. Go to the **Files changed** tab of the pull request.  
2. Click the pencil icon to edit the file.  
3. Make the change, and then commit it into the *same branch*.  
 
This pull request automatically updates with your new commit.
 
Let me know if you have any questions.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

Due to publishing freeze this week, this change won't go live until Monday, 6 May, or later.

**Pull request merged**
