### PR TITLE
Update site-and-site-system-prerequisites.md

### PR DESCRIPTION
**Pull request by cliffhobbs**
Changed "Reporting point" to "Reporting Services point".

### Summarize the change in the pull request title

Describe your change, specifically *why* you think it's needed.

Fixes #Issue_Number (if necessary)

@Article_Author please review (look at the `author` metadata tag)

### CODE REVIEW

**Comment by aczechowski** [comment]
Thanks @cliffhobbs for the contribution! Agreed that should reporting services point. (I hope I wasn't the one who changed it that way. 😨)

For proper Microsoft style, can you please drop the capitalization on "services" in both instances? For more information, see [Top 10 tips for Microsoft style and voice](https://docs.microsoft.com/style-guide/top-10-tips-style-voice#when-in-doubt-dont-capitalize).

To make the edit:
1. Go to the *Files changed* tab of the pull request.
2. Click the pencil icon to edit the file.
3. Make the change, and then commit it into the *same branch*.
This pull request automatically updates with your new commit.

Let me know if you have any questions.

**Comment by PRMerger14** [comment]
@cliffhobbs : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by cliffhobbs** [comment]
Done

**Comment by aczechowski** [comment]
Looks good, thanks @cliffhobbs!
#sign-off
*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 19 September) around 11:00 Pacific time.

**Pull request merged**
